### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by asppsa** [asppsa/archlinux-nix#12]
Hi,

It's been brought to my attention that I've failed to keep this package updated over the last 7 or so months.  In part this is because I managed to stuff up my Github notifications, but the other major contributing factor has been that I have stopped using Nix day-to-day due to a change in my employment situation.  As such, I think it makes sense for one or more people who are using Nix on the regular to take over the maintenance of this repo, and the associated AUR packages.

There are a couple of ways we could do this: I can give the maintainer(s) access to this existing repo and create co-maintainers in AUR; or someone could fork this project and continue maintenance in a fork instead.  I'm probably more in favour of the former as I have some hopes to be able to get actively involved in this project again at some point in the future, but happy to discuss this point further.

If you're interested, please speak up in this issue, and my apologies for the long delay on all the outstanding PRs!

**Comment by tudurom** [comment]
I'm all for it, I agree that this is the best solution, and I hope you turn to Nix again soon!

**Comment by asppsa** [comment]
@tudurom, over to you!  If there's anything you need from me, feel free to @ me, or get in touch by email.
