### ISSUE TITLE
SHA256 failure

### ISSUE THREAD

**Issue by hsyl20** [asppsa/archlinux-nix#8]
`archlinux-nix` fails to retrieve the sha256:

```
/usr/bin/archlinux-nix: SHA-256 hash mismatch in 'https://nixos.org/releases/nix/nix-2.3.1/nix-2.3.1-x86_64-linux.tar.xz'; expected Redirecting to https://releases.nixos.org/nix/nix-2.3.1/nix-2.3.1-x86_64-linux.tar.xz.sha256, got 107310e95a57f502b7ada41aa2c76a3d4aec18847ad864d0b233ca8f4452e9fc
```

A simple fix is to replace "nixos.org/releases" with "releases.nixos.org" at
https://github.com/asppsa/archlinux-nix/blob/126df06ec9c1d0cb59af71e5242d610c4787c91b/archlinux-nix#L59

**Comment by 573** [comment]
PR #10 fixes that.

**Comment by tudurom** [comment]
#10 merged, it's fixed!
